"""
Re-embed the AutoCAD block DWGs into app/dxf/block_data.py as base64.

Run this whenever a block in autocad/blocks/ changes, so the packaged exe
(which can't see the source folder) ships the latest block geometry.

    python tools/embed_blocks.py
"""

import base64
import os

ROOT      = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SRC_DIR   = os.path.join(ROOT, "autocad", "blocks")
OUT_FILE  = os.path.join(ROOT, "app", "dxf", "block_data.py")

BLOCKS = ("MTAP_BACKTAPER", "MTAP_GDT", "MTAP_DATUM")


def main() -> None:
    out = [
        "# Auto-generated by tools/embed_blocks.py — do not edit by hand.",
        "# DWG block files embedded as base64, extracted at runtime.",
        "import base64",
        "",
        "BLOCKS: dict[str, bytes] = {}",
        "",
    ]
    for name in BLOCKS:
        path = os.path.join(SRC_DIR, f"{name}.dwg")
        with open(path, "rb") as f:
            data = f.read()
        b64 = base64.b64encode(data).decode("ascii")
        chunks = [b64[i:i + 76] for i in range(0, len(b64), 76)]
        out.append(f"__{name} = (")
        out.extend(f'    "{c}"' for c in chunks)
        out.append(")")
        out.append(f"BLOCKS[\"{name}\"] = base64.b64decode(__{name})")
        out.append(f"# {name}: {len(data):,} bytes")
        out.append("")
        print(f"embedded {name}: {len(data):,} bytes")

    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"\nwrote {OUT_FILE}")


if __name__ == "__main__":
    main()
